#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"

GOOGLE_CREDENTIALS="$(bo show credential concourse-main performance-tests.performance-tests-uploader google-storage-key)" \
fly --target ci \
    execute \
    --include-ignored \
    --config pipeline/tasks/update-website.yaml \
    --input document-root="$cwd/fly-test-results" \
    --var destination=gs://performance-tests.devboclips.net
