#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"

EMAIL="$(bo show credential concourse-main performance-tests.config email)"
PASSWORD="$(bo show credential concourse-main performance-tests.config password)"
URL="https://teachers.boclips.com/videos?page=1&q=mathematics"

export EMAIL
export PASSWORD
export URL

fly --target ci \
    execute \
    --privileged \
    --config "$cwd/pipeline/tasks/lighthouse-ci.yaml" \
    --input source="$cwd"
