---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cypress/browsers
    tag: node10.16.0-chrome77

inputs:
- name: source
- name: release-manifests

params:
  ACHIEVE_LOGIN_URL:
  TEST_URL:
  EMAIL:
  PASSWORD:
  LHCI_TOKEN:

run:
  user: root
  path: sh
  args:
  - -ec
  - |-
    LHCI_BUILD_CONTEXT__CURRENT_HASH="$(git -C release-manifests rev-list --no-merges -n1 HEAD)"
    LHCI_BUILD_CONTEXT__CURRENT_BRANCH=master
    LHCI_BUILD_CONTEXT__COMMIT_MESSAGE="$(git -C release-manifests log --format=%s -n1 HEAD)"
    LHCI_BUILD_CONTEXT__AUTHOR="Boclips <engineering@boclips.com>"
    LHCI_BUILD_CONTEXT__AVATAR_URL="https://avatars2.githubusercontent.com/u/12545638?s=200&v=4"
    LHCI_BUILD_CONTEXT__COMMIT_TIME="$(git -C release-manifests log -n1 --pretty=%cI HEAD)"
    export LHCI_BUILD_CONTEXT__CURRENT_HASH
    export LHCI_BUILD_CONTEXT__CURRENT_BRANCH
    export LHCI_BUILD_CONTEXT__COMMIT_MESSAGE
    export LHCI_BUILD_CONTEXT__AUTHOR
    export LHCI_BUILD_CONTEXT__AVATAR_URL
    export LHCI_BUILD_CONTEXT__COMMIT_TIME
    (
    cd source
    npm ci
    npm run lint
    npx tsc ./main.ts
    mkdir .lighthouseci
    chown node:node .lighthouseci
    su node --command \
    "npx lhci collect --url=$TEST_URL"
    su node --command \
    "npx lhci upload"
    )

caches:
- path: ../../../home/chrome/.cache
- path: ../../../root/.npm
