---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cypress/browsers
    tag: node10.16.0-chrome77

inputs:
- name: source
- name: release-manifests

params:
  URL:
  EMAIL:
  PASSWORD:
  LHCI_TOKEN:

run:
  user: root
  path: sh
  args:
  - -ec
  - |-
    LHCI_BUILD_CONTEXT__CURRENT_HASH="$(git -C release-manifests rev-list --no-merges -n1 HEAD)"
    export LHCI_BUILD_CONTEXT__CURRENT_HASH
    (
    cd source
    npm ci
    npm run lint
    npx tsc ./main.ts
    mkdir .lighthouseci
    chown node:node .lighthouseci
    su node --command \
    "npx lhci collect"
    su node --command \
    "npx lhci upload"
    )

caches:
- path: ../../../home/chrome/.cache
- path: ../../../root/.npm
