---
jobs:

- name: run
  plan:
  - get: source
  - get: every-hour
    trigger: true
  - task: run
    file: source/pipeline/tasks/lighthouse-ci.yaml
    privileged: true
    params:
      # This gets us to the login. See lighthouserc.yaml for URL the test is
      # run against.
      URL: "https://teachers.boclips.com/"
      EMAIL: ((config.email))
      PASSWORD: ((config.password))

resources:

- name: source
  type: git
  icon: github-circle
  source:
    uri: https://github.com/boclips/performance-tests.git

- name: every-hour
  type: time
  icon: clock-outline
  source:
    interval: 1h
