---
jobs:

- name: run
  plan:
  - get: source
  - task: run
    file: source/pipeline/tasks/run.yaml
    privileged: true
    params:
      URL: ((config.url))
      EMAIL: ((config.email))
      PASSWORD: ((config.password))
  - task: update-website
    file: source/pipeline/tasks/update-website.yaml
    params:
      GOOGLE_CREDENTIALS: ((performance-tests-uploader.google-storage-key))
    input_mapping:
      document-root: test-results
    vars:
      destination: gs://performance-tests.devboclips.net

resources:

- name: source
  type: git
  icon: github-circle
  source:
    uri: https://github.com/boclips/performance-tests.git
