apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
namespace: tools
replicas:
- count: 1
  name: lhci-server
patches:
- path: domain.yaml
  target:
    group: extensions
    kind: Ingress
    version: v1beta1
- path: noncritical.yaml
  target:
    group: apps
    kind: StatefulSet
    version: v1
