- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: '/data'
    name: lhci-data-volume
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: lhci-data-volume
    persistentVolumeClaim:
      claimName: lhci-data-claim
